version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  build-and-deploy:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: aaronstillwell/circleci-runner-extended
          tag: $CIRCLE_SHA1,latest
      - docker/push:
          image: aaronstillwell/circleci-runner-extended
          tag: $CIRCLE_SHA1,latest

workflows:
  default:
    jobs:
      - build-and-deploy
# VS Code Extension Version: 1.0.1
